name: Lint

on:
    push:
    pull_request:

jobs:
    formatting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6
              with:
                  submodules: recursive

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: latest

            - name: Lint with make
              run: make lint
