name: Publish polonium.kwinscript

on:
    push:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
            contents: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v6
              with:
                  submodules: recursive

            - name: Install dependencies
              run: sudo apt-get install -y npm cargo

            - name: Build kwinscript
              run: make build

            - name: Build dbus-saver
              run: make dbus-build

            - name: Create release
              run: |
                  gh release delete nightly --yes || true
                  git push --delete origin refs/tags/nightly || true
                  gh release create nightly \
                    --prerelease \
                    --title "Development build" \
                    --notes "Get the latest version with all the new bugs and features." \
                    polonium.kwinscript \
                    dbus-saver/target/release/polonium-saver
